language: node_js
node_js: 5.5.0
sudo: required
install:
- npm install -g npm@2.7.5
- npm install
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
script:
- gulp
deploy:
  provider: gae
  keyfile: ./exploring-the-sutras-2155b0efcb90.json
  project: exploring-the-sutras
before_install:
- openssl aes-256-cbc -K $encrypted_099efd342a6e_key -iv $encrypted_099efd342a6e_iv
  -in exploring-the-sutras-2155b0efcb90.json.enc -out exploring-the-sutras-2155b0efcb90.json
  -d
