# [START runtime]
runtime: nodejs
vm: true
# [END runtime]

# Temporary setting to keep gcloud from uploading node_modules
skip_files:
 - ^node_modules$

handlers:

- url: /(.*\.(html|css|js))
  static_files: public/\1
  upload: public/(.*\.(html|css|js))

- url: /
  static_files: static/index.html
  upload: public/index.html
