const heartsutra = {
    title: [
        {romaji: 'Maka', kanji: ' ', hiragana: 'まか', english: '.'},
        {romaji: 'Hannya', kanji: ' ', hiragana: 'はんにゃ', english: '.'},
        {romaji: 'Haramitta', kanji: ' ', hiragana: 'はらみった', english: '.'},
        {romaji: 'Shin', kanji: '心', hiragana: 'しん', english: 'heart'},
        {romaji: 'Gyo', kanji: ' ', hiragana: 'ぎょ', english: '.'}
    ],
    sutra: [
        {romaji: 'kan', kanji: ' ', hiragana: 'かん', english: ' '},
        {romaji: 'ji', kanji: ' ', hiragana: 'じ', english: ' '},
        {romaji: 'zai', kanji: ' ', hiragana: 'ざい', english: ' '},
        {romaji: 'bo', kanji: ' ', hiragana: 'ぼ', english: ' '},
        {romaji: 'satsu', kanji: ' ', hiragana: 'さつ', english: ' '},
        {romaji: 'gyo', kanji: ' ', hiragana: 'ぎょ', english: ' '},
        {romaji: 'jin', kanji: ' ', hiragana: 'じん', english: ' '},
        {romaji: 'han', kanji: ' ', hiragana: 'はん', english: ' '},
        {romaji: 'nya', kanji: ' ', hiragana: 'にゃ', english: ' '},
        {romaji: 'ha', kanji: ' ', hiragana: 'は', english: ' '},
        {romaji: 'ra', kanji: ' ', hiragana: 'ら', english: ' '},
        {romaji: 'mit', kanji: ' ', hiragana: 'みっ', english: ' '},
        {romaji: 'ta', kanji: ' ', hiragana: 'た', english: ' '},
        {romaji: 'ji', kanji: ' ', hiragana: 'じ', english: ' '},
        {romaji: 'sho', kanji: ' ', hiragana: 'そ', english: ' '},
        {romaji: 'ken', kanji: ' ', hiragana: 'けん', english: ' '},
        {romaji: 'go', kanji: ' ', hiragana: 'ご', english: ' '},
        {romaji: 'on', kanji: ' ', hiragana: 'おん', english: ' '},
        {romaji: 'kai', kanji: ' ', hiragana: 'かい', english: ' '},
        {romaji: 'ku', kanji: ' ', hiragana: 'く', english: ' '},
        {romaji: 'do', kanji: ' ', hiragana: 'ど', english: ' '},
        {romaji: 'is', kanji: ' ', hiragana: 'いっ', english: ' '},
        {romaji: 'sai', kanji: ' ', hiragana: 'さい', english: ' '},
        {romaji: 'ku', kanji: ' ', hiragana: 'く', english: ' '},
        {romaji: 'yaku', kanji: ' ', hiragana: 'やく', english: ' '},
        {romaji: 'sha', kanji: ' ', hiragana: 'さ', english: ' '},
        {romaji: 'ri', kanji: ' ', hiragana: 'り', english: ' '},
        {romaji: 'shi', kanji: ' ', hiragana: 'し', english: ' '},
        {romaji: 'shiki', kanji: ' ', hiragana: 'しき', english: ' '},
        {romaji: 'fu', kanji: ' ', hiragana: 'ふ', english: ' '},
        {romaji: 'i', kanji: ' ', hiragana: 'い', english: ' '},
        {romaji: 'ku', kanji: ' ', hiragana: 'く', english: ' '},
        {romaji: 'ku', kanji: ' ', hiragana: 'く', english: ' '},
        {romaji: 'fu', kanji: ' ', hiragana: 'ふ', english: ' '},
        {romaji: 'i', kanji: ' ', hiragana: 'い', english: ' '},
        {romaji: 'shiki', kanji: ' ', hiragana: 'しき', english: ' '},
        {romaji: 'shiki', kanji: ' ', hiragana: 'しき', english: ' '},
        {romaji: 'soku', kanji: ' ', hiragana: 'そく', english: ' '},
        {romaji: 'ze', kanji: ' ', hiragana: 'ぜ', english: ' '},
        {romaji: 'ku', kanji: ' ', hiragana: 'く', english: ' '},
        {romaji: 'ku', kanji: ' ', hiragana: 'く', english: ' '},
        {romaji: 'soku', kanji: ' ', hiragana: 'そく', english: ' '},
        {romaji: 'ze', kanji: ' ', hiragana: 'ぜ', english: ' '},
        {romaji: 'shiki', kanji: ' ', hiragana: 'しき', english: ' '},
        {romaji: 'ju', kanji: ' ', hiragana: 'じゅ', english: ' '},
        {romaji: 'so', kanji: ' ', hiragana: 'そ', english: ' '},
        {romaji: 'gyo', kanji: ' ', hiragana: 'ぎょ', english: ' '},
        {romaji: 'shiki', kanji: ' ', hiragana: 'しき', english: ' '},
        {romaji: 'yaku', kanji: ' ', hiragana: 'やく', english: ' '},
        {romaji: 'bu', kanji: ' ', hiragana: 'ぶ', english: ' '},
        {romaji: 'nyo', kanji: ' ', hiragana: 'にょ', english: ' '},
        {romaji: 'ze', kanji: ' ', hiragana: 'ぜ', english: ' '},
        {romaji: 'sha', kanji: ' ', hiragana: 'さ', english: ' '},
        {romaji: 'ri', kanji: ' ', hiragana: 'り', english: ' '},
        {romaji: 'shi', kanji: ' ', hiragana: 'し', english: ' '},
        {romaji: 'ze', kanji: ' ', hiragana: 'ぜ', english: ' '},
        {romaji: 'sho', kanji: ' ', hiragana: 'そ', english: ' '},
        {romaji: 'ho', kanji: ' ', hiragana: 'ほ', english: ' '},
        {romaji: 'ku', kanji: ' ', hiragana: 'く', english: ' '},
        {romaji: 'so', kanji: ' ', hiragana: 'そ', english: ' '},
        {romaji: 'fu', kanji: ' ', hiragana: 'ふ', english: ' '},
        {romaji: 'sho', kanji: ' ', hiragana: 'そ', english: ' '},
        {romaji: 'fu', kanji: ' ', hiragana: 'ふ', english: ' '},
        {romaji: 'metsu', kanji: ' ', hiragana: 'めつ', english: ' '},
        {romaji: 'fu', kanji: ' ', hiragana: 'ふ', english: ' '},
        {romaji: 'ku', kanji: ' ', hiragana: 'く', english: ' '},
        {romaji: 'fu', kanji: ' ', hiragana: 'ふ', english: ' '},
        {romaji: 'jo', kanji: ' ', hiragana: 'じょ', english: ' '},
        {romaji: 'fu', kanji: ' ', hiragana: 'ふ', english: ' '},
        {romaji: 'zo', kanji: ' ', hiragana: 'ぞ', english: ' '},
        {romaji: 'fu', kanji: ' ', hiragana: 'ふ', english: ' '},
        {romaji: 'gen', kanji: ' ', hiragana: 'げん', english: ' '},
        {romaji: 'ze', kanji: ' ', hiragana: 'ぜ', english: ' '},
        {romaji: 'ko', kanji: ' ', hiragana: 'こ', english: ' '},
        {romaji: 'ku', kanji: ' ', hiragana: 'く', english: ' '},
        {romaji: 'chu', kanji: ' ', hiragana: 'ちゅ', english: ' '},
        {romaji: 'mu', kanji: '無', hiragana: 'む', english: 'No'},
        {romaji: 'shiki', kanji: ' ', hiragana: 'しき', english: ' '},
        {romaji: 'mu', kanji: '無', hiragana: 'む', english: 'No'},
        {romaji: 'ju', kanji: ' ', hiragana: 'じゅ', english: ' '},
        {romaji: 'so', kanji: ' ', hiragana: 'そ', english: ' '},
        {romaji: 'gyo', kanji: ' ', hiragana: 'ぎょ', english: ' '},
        {romaji: 'shiki', kanji: ' ', hiragana: 'しき', english: ' '},
        {romaji: 'mu', kanji: '無', hiragana: 'む', english: 'No'},
        {romaji: 'gen', kanji: ' ', hiragana: 'げん', english: ' '},
        {romaji: 'ni', kanji: ' ', hiragana: 'に', english: ' '},
        {romaji: 'bi', kanji: ' ', hiragana: 'び', english: ' '},
        {romaji: 'ze', kanji: ' ', hiragana: 'ぜ', english: ' '},
        {romaji: 'shin', kanji: '心', hiragana: 'しん', english: 'heart'},
        {romaji: 'ni', kanji: ' ', hiragana: 'に', english: ' '},
        {romaji: 'mu', kanji: '無', hiragana: 'む', english: 'No'},
        {romaji: 'shiki', kanji: ' ', hiragana: 'しき', english: ' '},
        {romaji: 'sho', kanji: ' ', hiragana: 'そ', english: ' '},
        {romaji: 'ko', kanji: ' ', hiragana: 'こ', english: ' '},
        {romaji: 'mi', kanji: ' ', hiragana: 'み', english: ' '},
        {romaji: 'soku', kanji: ' ', hiragana: 'そく', english: ' '},
        {romaji: 'ho', kanji: ' ', hiragana: 'ほ', english: ' '},
        {romaji: 'mu', kanji: '無', hiragana: 'む', english: 'No'},
        {romaji: 'gen', kanji: ' ', hiragana: 'げん', english: ' '},
        {romaji: 'kai', kanji: ' ', hiragana: 'かい', english: ' '},
        {romaji: 'nai', kanji: ' ', hiragana: 'んあい', english: ' '},
        {romaji: 'shi', kanji: ' ', hiragana: 'し', english: ' '},
        {romaji: 'mu', kanji: '無', hiragana: 'む', english: 'No'},
        {romaji: 'i', kanji: ' ', hiragana: 'い', english: ' '},
        {romaji: 'shiki', kanji: ' ', hiragana: 'しき', english: ' '},
        {romaji: 'kai', kanji: ' ', hiragana: 'かい', english: ' '},
        {romaji: 'mu', kanji: '無', hiragana: 'む', english: 'No'},
        {romaji: 'mu', kanji: '無', hiragana: 'む', english: 'No'},
        {romaji: 'myo', kanji: ' ', hiragana: 'みょ', english: ' '},
        {romaji: 'yaku', kanji: ' ', hiragana: 'やく', english: ' '},
        {romaji: 'mu', kanji: '無', hiragana: 'む', english: 'No'},
        {romaji: 'mu', kanji: '無', hiragana: 'む', english: 'No'},
        {romaji: 'myo', kanji: ' ', hiragana: 'みょ', english: ' '},
        {romaji: 'jin', kanji: ' ', hiragana: 'じん', english: ' '},
        {romaji: 'nai', kanji: ' ', hiragana: 'んあい', english: ' '},
        {romaji: 'shi', kanji: ' ', hiragana: 'し', english: ' '},
        {romaji: 'mu', kanji: '無', hiragana: 'む', english: 'No'},
        {romaji: 'ro', kanji: ' ', hiragana: 'ろ', english: ' '},
        {romaji: 'shi', kanji: ' ', hiragana: 'し', english: ' '},
        {romaji: 'yaku', kanji: ' ', hiragana: 'やく', english: ' '},
        {romaji: 'mu', kanji: '無', hiragana: 'む', english: 'No'},
        {romaji: 'ro', kanji: ' ', hiragana: 'ろ', english: ' '},
        {romaji: 'shi', kanji: ' ', hiragana: 'し', english: ' '},
        {romaji: 'jin', kanji: ' ', hiragana: 'じん', english: ' '},
        {romaji: 'mu', kanji: '無', hiragana: 'む', english: 'No'},
        {romaji: 'ku', kanji: ' ', hiragana: 'く', english: ' '},
        {romaji: 'shu', kanji: ' ', hiragana: 'す', english: ' '},
        {romaji: 'metsu', kanji: ' ', hiragana: 'めつ', english: ' '},
        {romaji: 'do', kanji: ' ', hiragana: 'ど', english: ' '},
        {romaji: 'mu', kanji: '無', hiragana: 'む', english: 'No'},
        {romaji: 'chi', kanji: ' ', hiragana: 'ち', english: ' '},
        {romaji: 'yaku', kanji: ' ', hiragana: 'やく', english: ' '},
        {romaji: 'mu', kanji: '無', hiragana: 'む', english: 'No'},
        {romaji: 'toku', kanji: ' ', hiragana: 'とく', english: ' '},
        {romaji: 'i', kanji: ' ', hiragana: 'い', english: ' '},
        {romaji: 'mu', kanji: '無', hiragana: 'む', english: 'No'},
        {romaji: 'sho', kanji: ' ', hiragana: 'そ', english: ' '},
        {romaji: 'tok', kanji: ' ', hiragana: 'とっ', english: ' '},
        {romaji: 'ko', kanji: ' ', hiragana: 'こ', english: ' '},
        {romaji: 'bo', kanji: ' ', hiragana: 'ぼ', english: ' '},
        {romaji: 'dai', kanji: ' ', hiragana: 'だい', english: ' '},
        {romaji: 'sat', kanji: ' ', hiragana: 'さっ', english: ' '},
        {romaji: 'ta', kanji: ' ', hiragana: 'た', english: ' '},
        {romaji: 'e', kanji: ' ', hiragana: 'え', english: ' '},
        {romaji: 'han', kanji: ' ', hiragana: 'はん', english: ' '},
        {romaji: 'nya', kanji: ' ', hiragana: 'にゃ', english: ' '},
        {romaji: 'ha', kanji: ' ', hiragana: 'は', english: ' '},
        {romaji: 'ra', kanji: ' ', hiragana: 'ら', english: ' '},
        {romaji: 'mit', kanji: ' ', hiragana: 'みっ', english: ' '},
        {romaji: 'ta', kanji: ' ', hiragana: 'た', english: ' '},
        {romaji: 'ko', kanji: ' ', hiragana: 'こ', english: ' '},
        {romaji: 'shin', kanji: '心', hiragana: 'しん', english: 'heart'},
        {romaji: 'mu', kanji: '無', hiragana: 'む', english: 'No'},
        {romaji: 'ke', kanji: ' ', hiragana: 'け', english: ' '},
        {romaji: 'ge', kanji: ' ', hiragana: 'げ', english: ' '},
        {romaji: 'mu', kanji: '無', hiragana: 'む', english: 'No'},
        {romaji: 'ke', kanji: ' ', hiragana: 'け', english: ' '},
        {romaji: 'ge', kanji: ' ', hiragana: 'げ', english: ' '},
        {romaji: 'ko', kanji: ' ', hiragana: 'こ', english: ' '},
        {romaji: 'mu', kanji: '無', hiragana: 'む', english: 'No'},
        {romaji: 'u', kanji: ' ', hiragana: 'う', english: ' '},
        {romaji: 'ku', kanji: ' ', hiragana: 'く', english: ' '},
        {romaji: 'fu', kanji: ' ', hiragana: 'ふ', english: ' '},
        {romaji: 'on', kanji: ' ', hiragana: 'おん', english: ' '},
        {romaji: 'ri', kanji: ' ', hiragana: 'り', english: ' '},
        {romaji: 'is', kanji: ' ', hiragana: 'いっ', english: ' '},
        {romaji: 'sai', kanji: ' ', hiragana: 'さい', english: ' '},
        {romaji: 'ten', kanji: ' ', hiragana: 'てん', english: ' '},
        {romaji: 'do', kanji: ' ', hiragana: 'ど', english: ' '},
        {romaji: 'mu', kanji: '無', hiragana: 'む', english: 'No'},
        {romaji: 'so', kanji: ' ', hiragana: 'そ', english: ' '},
        {romaji: 'ku', kanji: ' ', hiragana: 'く', english: ' '},
        {romaji: 'gyo', kanji: ' ', hiragana: 'ぎょ', english: ' '},
        {romaji: 'ne', kanji: ' ', hiragana: 'ね', english: ' '},
        {romaji: 'han', kanji: ' ', hiragana: 'はん', english: ' '},
        {romaji: 'san', kanji: ' ', hiragana: 'さん', english: ' '},
        {romaji: 'ze', kanji: ' ', hiragana: 'ぜ', english: ' '},
        {romaji: 'sho', kanji: ' ', hiragana: 'そ', english: ' '},
        {romaji: 'butsu', kanji: ' ', hiragana: 'ぶつ', english: ' '},
        {romaji: 'e', kanji: ' ', hiragana: 'え', english: ' '},
        {romaji: 'han', kanji: ' ', hiragana: 'はん', english: ' '},
        {romaji: 'nya', kanji: ' ', hiragana: 'にゃ', english: ' '},
        {romaji: 'ha', kanji: ' ', hiragana: 'は', english: ' '},
        {romaji: 'ra', kanji: ' ', hiragana: 'ら', english: ' '},
        {romaji: 'mit', kanji: ' ', hiragana: 'みっ', english: ' '},
        {romaji: 'ta', kanji: ' ', hiragana: 'た', english: ' '},
        {romaji: 'ko', kanji: ' ', hiragana: 'こ', english: ' '},
        {romaji: 'toku', kanji: ' ', hiragana: 'とく', english: ' '},
        {romaji: 'a', kanji: ' ', hiragana: 'あ', english: ' '},
        {romaji: 'noku', kanji: ' ', hiragana: 'んおく', english: ' '},
        {romaji: 'ta', kanji: ' ', hiragana: 'た', english: ' '},
        {romaji: 'ra', kanji: ' ', hiragana: 'ら', english: ' '},
        {romaji: 'sam', kanji: ' ', hiragana: 'さっ', english: ' '},
        {romaji: 'myaku', kanji: ' ', hiragana: 'みゃく', english: ' '},
        {romaji: 'sam', kanji: ' ', hiragana: 'さん', english: ' '},
        {romaji: 'bo', kanji: ' ', hiragana: 'ぼ', english: ' '},
        {romaji: 'dai', kanji: ' ', hiragana: 'だい', english: ' '},
        {romaji: 'ko', kanji: ' ', hiragana: 'こ', english: ' '},
        {romaji: 'chi', kanji: ' ', hiragana: 'ち', english: ' '},
        {romaji: 'han', kanji: ' ', hiragana: 'はん', english: ' '},
        {romaji: 'nya', kanji: ' ', hiragana: 'にゃ', english: ' '},
        {romaji: 'ha', kanji: ' ', hiragana: 'は', english: ' '},
        {romaji: 'ra', kanji: ' ', hiragana: 'ら', english: ' '},
        {romaji: 'mi', kanji: ' ', hiragana: 'み', english: ' '},
        {romaji: 'ta', kanji: ' ', hiragana: 'た', english: ' '},
        {romaji: 'ze', kanji: ' ', hiragana: 'ぜ', english: ' '},
        {romaji: 'dai', kanji: ' ', hiragana: 'だい', english: ' '},
        {romaji: 'jin', kanji: ' ', hiragana: 'じん', english: ' '},
        {romaji: 'shu', kanji: ' ', hiragana: 'す', english: ' '},
        {romaji: 'ze', kanji: ' ', hiragana: 'ぜ', english: ' '},
        {romaji: 'dai', kanji: ' ', hiragana: 'だい', english: ' '},
        {romaji: 'myo', kanji: ' ', hiragana: 'みょ', english: ' '},
        {romaji: 'shu', kanji: ' ', hiragana: 'す', english: ' '},
        {romaji: 'ze', kanji: ' ', hiragana: 'ぜ', english: ' '},
        {romaji: 'mu', kanji: '無', hiragana: 'む', english: 'No'},
        {romaji: 'jo', kanji: ' ', hiragana: 'じょ', english: ' '},
        {romaji: 'shu', kanji: ' ', hiragana: 'す', english: ' '},
        {romaji: 'ze', kanji: ' ', hiragana: 'ぜ', english: ' '},
        {romaji: 'mu', kanji: '無', hiragana: 'む', english: 'No'},
        {romaji: 'to', kanji: ' ', hiragana: 'と', english: ' '},
        {romaji: 'do', kanji: ' ', hiragana: 'ど', english: ' '},
        {romaji: 'shu', kanji: ' ', hiragana: 'す', english: ' '},
        {romaji: 'no', kanji: ' ', hiragana: 'の', english: ' '},
        {romaji: 'jo', kanji: ' ', hiragana: 'じょ', english: ' '},
        {romaji: 'is', kanji: ' ', hiragana: 'いっ', english: ' '},
        {romaji: 'sai', kanji: ' ', hiragana: 'さい', english: ' '},
        {romaji: 'ku', kanji: ' ', hiragana: 'く', english: ' '},
        {romaji: 'shin', kanji: '心', hiragana: 'しん', english: 'heart'},
        {romaji: 'jitsu', kanji: ' ', hiragana: 'じつ', english: ' '},
        {romaji: 'fu', kanji: ' ', hiragana: 'ふ', english: ' '},
        {romaji: 'ko', kanji: ' ', hiragana: 'こ', english: ' '},
        {romaji: 'ko', kanji: ' ', hiragana: 'こ', english: ' '},
        {romaji: 'setsu', kanji: ' ', hiragana: 'せつ', english: ' '},
        {romaji: 'han', kanji: ' ', hiragana: 'はん', english: ' '},
        {romaji: 'nya', kanji: ' ', hiragana: 'にゃ', english: ' '},
        {romaji: 'ha', kanji: ' ', hiragana: 'は', english: ' '},
        {romaji: 'ra', kanji: ' ', hiragana: 'ら', english: ' '},
        {romaji: 'mit', kanji: ' ', hiragana: 'みっ', english: ' '},
        {romaji: 'ta', kanji: ' ', hiragana: 'た', english: ' '},
        {romaji: 'shu', kanji: ' ', hiragana: 'す', english: ' '},
        {romaji: 'soku', kanji: ' ', hiragana: 'そく', english: ' '},
        {romaji: 'setsu', kanji: ' ', hiragana: 'せつ', english: ' '},
        {romaji: 'shu', kanji: ' ', hiragana: 'す', english: ' '},
        {romaji: 'watsu', kanji: ' ', hiragana: 'わつ', english: ' '},
        {romaji: 'gya', kanji: ' ', hiragana: 'ぎゃ', english: ' '},
        {romaji: 'te', kanji: ' ', hiragana: 'て', english: ' '},
        {romaji: 'gya', kanji: ' ', hiragana: 'ぎゃ', english: ' '},
        {romaji: 'te', kanji: ' ', hiragana: 'て', english: ' '},
        {romaji: 'ha', kanji: ' ', hiragana: 'は', english: ' '},
        {romaji: 'ra', kanji: ' ', hiragana: 'ら', english: ' '},
        {romaji: 'gya', kanji: ' ', hiragana: 'ぎゃ', english: ' '},
        {romaji: 'te', kanji: ' ', hiragana: 'て', english: ' '},
        {romaji: 'hara', kanji: ' ', hiragana: 'はら', english: ' '},
        {romaji: 'so', kanji: ' ', hiragana: 'そ', english: ' '},
        {romaji: 'gya', kanji: ' ', hiragana: 'ぎゃ', english: ' '},
        {romaji: 'te', kanji: ' ', hiragana: 'て', english: ' '},
        {romaji: 'bo', kanji: ' ', hiragana: 'ぼ', english: ' '},
        {romaji: 'ji', kanji: ' ', hiragana: 'じ', english: ' '},
        {romaji: 'sowa', kanji: ' ', hiragana: 'そわ', english: ' '},
        {romaji: 'ka', kanji: ' ', hiragana: 'か', english: ' '},
        {romaji: 'han', kanji: ' ', hiragana: 'はん', english: ' '},
        {romaji: 'nya', kanji: ' ', hiragana: 'にゃ', english: ' '},
        {romaji: 'shin', kanji: '心', hiragana: 'しん', english: 'heart'},
        {romaji: 'gyo', kanji: ' ', hiragana: 'ぎょ', english: ' '}
    ]
};

module.exports = heartsutra;