const heartsutra = {
    sutra: [
        {key: '001', kanji: '觀', romaji: 'kan', hiragana: 'かん', english: '?'},
        {key: '002', kanji: '自', romaji: 'ji', hiragana: 'じ', english: 'self'},
        {key: '003', kanji: '在', romaji: 'zai', hiragana: 'ざい', english: 'residing in'},
        {key: '004', kanji: '菩', romaji: 'bo', hiragana: 'ぼ', english: 'bodhi'},
        {key: '005', kanji: '薩', romaji: 'satsu', hiragana: 'さつ', english: 'sattva'},
        {key: '006', kanji: '行', romaji: 'gyō', hiragana: 'ぎょう', english: 'thing?'},
        {key: '008', kanji: '深', romaji: 'jin', hiragana: 'じん', english: 'profound'},
        {key: '009', kanji: '般', romaji: 'han', hiragana: 'はん', english: '?'},
        {key: '010', kanji: '若', romaji: 'nya', hiragana: 'にゃ', english: '?'},
        {key: '011', kanji: '波', romaji: 'ha', hiragana: 'は', english: '?'},
        {key: '012', kanji: '羅', romaji: 'ra', hiragana: 'ら', english: '?'},
        {key: '013', kanji: '蜜', romaji: 'mit', hiragana: 'みっ', english: '?'},
        {key: '014', kanji: '多', romaji: 'ta', hiragana: 'た', english: '?'},
        {key: '015', kanji: '時', romaji: 'ji', hiragana: 'じ', english: 'time?'},
        {key: '016', kanji: '照', romaji: 'shō', hiragana: 'しょう', english: 'illumination'},
        {key: '017', kanji: '見', romaji: 'ken', hiragana: 'けん', english: 'see'},
        {key: '018', kanji: '五', romaji: 'go', hiragana: 'ご', english: 'five'},
        {key: '019', kanji: '蘊', romaji: 'on', hiragana: 'うん', english: 'skhanda'},
        {key: '020', kanji: '皆', romaji: 'kai', hiragana: 'かい', english: 'everyone?'},
        {key: '021', kanji: '空', romaji: 'kū', hiragana: 'くう', english: 'emptiness'},
        {key: '022', kanji: '度', romaji: 'do', hiragana: 'ど', english: 'degree?'},
        {key: '023', kanji: '一', romaji: 'is', hiragana: 'いっ', english: 'one'},
        {key: '024', kanji: ' ', romaji: 'sai', hiragana: 'さい', english: ' '},
        {key: '025', kanji: ' ', romaji: 'ku', hiragana: 'く', english: ' '},
        {key: '026', kanji: ' ', romaji: 'yaku', hiragana: 'やく', english: ' '},
        {key: '027', kanji: ' ', romaji: 'sha', hiragana: 'さ', english: ' '},
        {key: '028', kanji: ' ', romaji: 'ri', hiragana: 'り', english: ' '},
        {key: '029', kanji: ' ', romaji: 'shi', hiragana: 'し', english: ' '},
        {key: '030', kanji: ' ', romaji: 'shiki', hiragana: 'しき', english: ' '},
        {key: '031', kanji: ' ', romaji: 'fu', hiragana: 'ふ', english: ' '},
        {key: '032', kanji: ' ', romaji: 'i', hiragana: 'い', english: ' '},
        {key: '033', kanji: ' ', romaji: 'ku', hiragana: 'く', english: ' '},
        {key: '034', kanji: ' ', romaji: 'ku', hiragana: 'く', english: ' '},
        {key: '035', kanji: ' ', romaji: 'fu', hiragana: 'ふ', english: ' '},
        {key: '036', kanji: ' ', romaji: 'i', hiragana: 'い', english: ' '},
        {key: '037', kanji: ' ', romaji: 'shiki', hiragana: 'しき', english: ' '},
        {key: '038', kanji: ' ', romaji: 'shiki', hiragana: 'しき', english: ' '},
        {key: '039', kanji: ' ', romaji: 'soku', hiragana: 'そく', english: ' '},
        {key: '040', kanji: ' ', romaji: 'ze', hiragana: 'ぜ', english: ' '},
        {key: '041', kanji: ' ', romaji: 'ku', hiragana: 'く', english: ' '},
        {key: '042', kanji: ' ', romaji: 'ku', hiragana: 'く', english: ' '},
        {key: '043', kanji: ' ', romaji: 'soku', hiragana: 'そく', english: ' '},
        {key: '044', kanji: ' ', romaji: 'ze', hiragana: 'ぜ', english: ' '},
        {key: '045', kanji: ' ', romaji: 'shiki', hiragana: 'しき', english: ' '},
        {key: '046', kanji: ' ', romaji: 'ju', hiragana: 'じゅ', english: ' '},
        {key: '047', kanji: ' ', romaji: 'so', hiragana: 'そ', english: ' '},
        {key: '048', kanji: ' ', romaji: 'gyo', hiragana: 'ぎょ', english: '.'},
        {key: '049', kanji: ' ', romaji: 'shiki', hiragana: 'しき', english: ' '},
        {key: '050', kanji: ' ', romaji: 'yaku', hiragana: 'やく', english: ' '},
        {key: '051', kanji: ' ', romaji: 'bu', hiragana: 'ぶ', english: ' '},
        {key: '052', kanji: ' ', romaji: 'nyo', hiragana: 'にょ', english: ' '},
        {key: '053', kanji: ' ', romaji: 'ze', hiragana: 'ぜ', english: ' '},
        {key: '054', kanji: ' ', romaji: 'sha', hiragana: 'さ', english: ' '},
        {key: '055', kanji: ' ', romaji: 'ri', hiragana: 'り', english: ' '},
        {key: '056', kanji: ' ', romaji: 'shi', hiragana: 'し', english: ' '},
        {key: '057', kanji: ' ', romaji: 'ze', hiragana: 'ぜ', english: ' '},
        {key: '058', kanji: ' ', romaji: 'sho', hiragana: 'そ', english: ' '},
        {key: '059', kanji: ' ', romaji: 'ho', hiragana: 'ほ', english: ' '},
        {key: '060', kanji: ' ', romaji: 'ku', hiragana: 'く', english: ' '},
        {key: '061', kanji: ' ', romaji: 'so', hiragana: 'そ', english: ' '},
        {key: '062', kanji: ' ', romaji: 'fu', hiragana: 'ふ', english: ' '},
        {key: '063', kanji: ' ', romaji: 'sho', hiragana: 'そ', english: ' '},
        {key: '064', kanji: ' ', romaji: 'fu', hiragana: 'ふ', english: ' '},
        {key: '065', kanji: ' ', romaji: 'metsu', hiragana: 'めつ', english: ' '},
        {key: '066', kanji: ' ', romaji: 'fu', hiragana: 'ふ', english: ' '},
        {key: '067', kanji: ' ', romaji: 'ku', hiragana: 'く', english: ' '},
        {key: '068', kanji: ' ', romaji: 'fu', hiragana: 'ふ', english: ' '},
        {key: '069', kanji: ' ', romaji: 'jo', hiragana: 'じょ', english: ' '},
        {key: '070', kanji: ' ', romaji: 'fu', hiragana: 'ふ', english: ' '},
        {key: '071', kanji: ' ', romaji: 'zo', hiragana: 'ぞ', english: ' '},
        {key: '072', kanji: ' ', romaji: 'fu', hiragana: 'ふ', english: ' '},
        {key: '073', kanji: ' ', romaji: 'gen', hiragana: 'げん', english: ' '},
        {key: '074', kanji: ' ', romaji: 'ze', hiragana: 'ぜ', english: ' '},
        {key: '075', kanji: ' ', romaji: 'ko', hiragana: 'こ', english: ' '},
        {key: '076', kanji: ' ', romaji: 'ku', hiragana: 'く', english: ' '},
        {key: '077', kanji: ' ', romaji: 'chu', hiragana: 'ちゅ', english: ' '},
        {key: '078', kanji: '無', romaji: 'mu', hiragana: 'む', english: 'No'},
        {key: '079', kanji: ' ', romaji: 'shiki', hiragana: 'しき', english: ' '},
        {key: '080', kanji: '無', romaji: 'mu', hiragana: 'む', english: 'No'},
        {key: '081', kanji: ' ', romaji: 'ju', hiragana: 'じゅ', english: ' '},
        {key: '082', kanji: ' ', romaji: 'so', hiragana: 'そ', english: ' '},
        {key: '083', kanji: ' ', romaji: 'gyo', hiragana: 'ぎょ', english: '.'},
        {key: '084', kanji: ' ', romaji: 'shiki', hiragana: 'しき', english: ' '},
        {key: '085', kanji: '無', romaji: 'mu', hiragana: 'む', english: 'No'},
        {key: '086', kanji: ' ', romaji: 'gen', hiragana: 'げん', english: ' '},
        {key: '087', kanji: ' ', romaji: 'ni', hiragana: 'に', english: ' '},
        {key: '088', kanji: ' ', romaji: 'bi', hiragana: 'び', english: ' '},
        {key: '089', kanji: ' ', romaji: 'ze', hiragana: 'ぜ', english: ' '},
        {key: '090', kanji: '心', romaji: 'shin', hiragana: 'しん', english: 'heart'},
        {key: '091', kanji: ' ', romaji: 'ni', hiragana: 'に', english: ' '},
        {key: '092', kanji: '無', romaji: 'mu', hiragana: 'む', english: 'No'},
        {key: '093', kanji: ' ', romaji: 'shiki', hiragana: 'しき', english: ' '},
        {key: '094', kanji: ' ', romaji: 'sho', hiragana: 'そ', english: ' '},
        {key: '095', kanji: ' ', romaji: 'ko', hiragana: 'こ', english: ' '},
        {key: '096', kanji: ' ', romaji: 'mi', hiragana: 'み', english: ' '},
        {key: '097', kanji: ' ', romaji: 'soku', hiragana: 'そく', english: ' '},
        {key: '098', kanji: ' ', romaji: 'ho', hiragana: 'ほ', english: ' '},
        {key: '099', kanji: '無', romaji: 'mu', hiragana: 'む', english: 'No'},
        {key: '100', kanji: ' ', romaji: 'gen', hiragana: 'げん', english: ' '},
        {key: '101', kanji: ' ', romaji: 'kai', hiragana: 'かい', english: ' '},
        {key: '102', kanji: ' ', romaji: 'nai', hiragana: 'んあい', english: ' '},
        {key: '103', kanji: ' ', romaji: 'shi', hiragana: 'し', english: ' '},
        {key: '104', kanji: '無', romaji: 'mu', hiragana: 'む', english: 'No'},
        {key: '105', kanji: ' ', romaji: 'i', hiragana: 'い', english: ' '},
        {key: '106', kanji: ' ', romaji: 'shiki', hiragana: 'しき', english: ' '},
        {key: '107', kanji: ' ', romaji: 'kai', hiragana: 'かい', english: ' '},
        {key: '108', kanji: '無', romaji: 'mu', hiragana: 'む', english: 'No'},
        {key: '109', kanji: '無', romaji: 'mu', hiragana: 'む', english: 'No'},
        {key: '110', kanji: ' ', romaji: 'myo', hiragana: 'みょ', english: ' '},
        {key: '111', kanji: ' ', romaji: 'yaku', hiragana: 'やく', english: ' '},
        {key: '112', kanji: '無', romaji: 'mu', hiragana: 'む', english: 'No'},
        {key: '113', kanji: '無', romaji: 'mu', hiragana: 'む', english: 'No'},
        {key: '114', kanji: ' ', romaji: 'myo', hiragana: 'みょ', english: ' '},
        {key: '115', kanji: ' ', romaji: 'jin', hiragana: 'じん', english: ' '},
        {key: '116', kanji: ' ', romaji: 'nai', hiragana: 'んあい', english: ' '},
        {key: '117', kanji: ' ', romaji: 'shi', hiragana: 'し', english: ' '},
        {key: '118', kanji: '無', romaji: 'mu', hiragana: 'む', english: 'No'},
        {key: '119', kanji: ' ', romaji: 'ro', hiragana: 'ろ', english: ' '},
        {key: '120', kanji: ' ', romaji: 'shi', hiragana: 'し', english: ' '},
        {key: '121', kanji: ' ', romaji: 'yaku', hiragana: 'やく', english: ' '},
        {key: '122', kanji: '無', romaji: 'mu', hiragana: 'む', english: 'No'},
        {key: '123', kanji: ' ', romaji: 'ro', hiragana: 'ろ', english: ' '},
        {key: '124', kanji: ' ', romaji: 'shi', hiragana: 'し', english: ' '},
        {key: '125', kanji: ' ', romaji: 'jin', hiragana: 'じん', english: ' '},
        {key: '126', kanji: '無', romaji: 'mu', hiragana: 'む', english: 'No'},
        {key: '127', kanji: ' ', romaji: 'ku', hiragana: 'く', english: ' '},
        {key: '128', kanji: ' ', romaji: 'shu', hiragana: 'す', english: ' '},
        {key: '129', kanji: ' ', romaji: 'metsu', hiragana: 'めつ', english: ' '},
        {key: '130', kanji: ' ', romaji: 'do', hiragana: 'ど', english: ' '},
        {key: '131', kanji: '無', romaji: 'mu', hiragana: 'む', english: 'No'},
        {key: '132', kanji: ' ', romaji: 'chi', hiragana: 'ち', english: ' '},
        {key: '133', kanji: ' ', romaji: 'yaku', hiragana: 'やく', english: ' '},
        {key: '134', kanji: '無', romaji: 'mu', hiragana: 'む', english: 'No'},
        {key: '135', kanji: ' ', romaji: 'toku', hiragana: 'とく', english: ' '},
        {key: '136', kanji: ' ', romaji: 'i', hiragana: 'い', english: ' '},
        {key: '137', kanji: '無', romaji: 'mu', hiragana: 'む', english: 'No'},
        {key: '138', kanji: ' ', romaji: 'sho', hiragana: 'そ', english: ' '},
        {key: '139', kanji: ' ', romaji: 'tok', hiragana: 'とっ', english: ' '},
        {key: '140', kanji: ' ', romaji: 'ko', hiragana: 'こ', english: ' '},
        {key: '141', kanji: ' ', romaji: 'bo', hiragana: 'ぼ', english: ' '},
        {key: '142', kanji: ' ', romaji: 'dai', hiragana: 'だい', english: ' '},
        {key: '143', kanji: ' ', romaji: 'sat', hiragana: 'さっ', english: ' '},
        {key: '144', kanji: ' ', romaji: 'ta', hiragana: 'た', english: ' '},
        {key: '145', kanji: ' ', romaji: 'e', hiragana: 'え', english: ' '},
        {key: '146', kanji: ' ', romaji: 'han', hiragana: 'はん', english: ' '},
        {key: '147', kanji: ' ', romaji: 'nya', hiragana: 'にゃ', english: ' '},
        {key: '148', kanji: ' ', romaji: 'ha', hiragana: 'は', english: ' '},
        {key: '149', kanji: ' ', romaji: 'ra', hiragana: 'ら', english: ' '},
        {key: '150', kanji: ' ', romaji: 'mit', hiragana: 'みっ', english: ' '},
        {key: '151', kanji: '多', romaji: 'ta', hiragana: 'た', english: ' '},
        {key: '152', kanji: ' ', romaji: 'ko', hiragana: 'こ', english: ' '},
        {key: '153', kanji: '心', romaji: 'shin', hiragana: 'しん', english: 'heart'},
        {key: '154', kanji: '無', romaji: 'mu', hiragana: 'む', english: 'No'},
        {key: '155', kanji: ' ', romaji: 'ke', hiragana: 'け', english: ' '},
        {key: '156', kanji: ' ', romaji: 'ge', hiragana: 'げ', english: ' '},
        {key: '157', kanji: '無', romaji: 'mu', hiragana: 'む', english: 'No'},
        {key: '158', kanji: ' ', romaji: 'ke', hiragana: 'け', english: ' '},
        {key: '159', kanji: ' ', romaji: 'ge', hiragana: 'げ', english: ' '},
        {key: '160', kanji: ' ', romaji: 'ko', hiragana: 'こ', english: ' '},
        {key: '161', kanji: '無', romaji: 'mu', hiragana: 'む', english: 'No'},
        {key: '162', kanji: ' ', romaji: 'u', hiragana: 'う', english: ' '},
        {key: '163', kanji: ' ', romaji: 'ku', hiragana: 'く', english: ' '},
        {key: '164', kanji: ' ', romaji: 'fu', hiragana: 'ふ', english: ' '},
        {key: '165', kanji: ' ', romaji: 'on', hiragana: 'おん', english: ' '},
        {key: '166', kanji: ' ', romaji: 'ri', hiragana: 'り', english: ' '},
        {key: '167', kanji: ' ', romaji: 'is', hiragana: 'いっ', english: ' '},
        {key: '168', kanji: ' ', romaji: 'sai', hiragana: 'さい', english: ' '},
        {key: '169', kanji: ' ', romaji: 'ten', hiragana: 'てん', english: ' '},
        {key: '170', kanji: ' ', romaji: 'do', hiragana: 'ど', english: ' '},
        {key: '171', kanji: '無', romaji: 'mu', hiragana: 'む', english: 'No'},
        {key: '172', kanji: ' ', romaji: 'so', hiragana: 'そ', english: ' '},
        {key: '173', kanji: ' ', romaji: 'ku', hiragana: 'く', english: ' '},
        {key: '174', kanji: ' ', romaji: 'gyo', hiragana: 'ぎょ', english: '.'},
        {key: '175', kanji: ' ', romaji: 'ne', hiragana: 'ね', english: ' '},
        {key: '176', kanji: ' ', romaji: 'han', hiragana: 'はん', english: ' '},
        {key: '177', kanji: ' ', romaji: 'san', hiragana: 'さん', english: ' '},
        {key: '178', kanji: ' ', romaji: 'ze', hiragana: 'ぜ', english: ' '},
        {key: '179', kanji: ' ', romaji: 'sho', hiragana: 'そ', english: ' '},
        {key: '180', kanji: ' ', romaji: 'butsu', hiragana: 'ぶつ', english: ' '},
        {key: '181', kanji: ' ', romaji: 'e', hiragana: 'え', english: ' '},
        {key: '182', kanji: ' ', romaji: 'han', hiragana: 'はん', english: ' '},
        {key: '183', kanji: ' ', romaji: 'nya', hiragana: 'にゃ', english: ' '},
        {key: '184', kanji: ' ', romaji: 'ha', hiragana: 'は', english: ' '},
        {key: '185', kanji: ' ', romaji: 'ra', hiragana: 'ら', english: ' '},
        {key: '186', kanji: ' ', romaji: 'mit', hiragana: 'みっ', english: ' '},
        {key: '187', kanji: '多', romaji: 'ta', hiragana: 'た', english: ' '},
        {key: '188', kanji: ' ', romaji: 'ko', hiragana: 'こ', english: ' '},
        {key: '189', kanji: ' ', romaji: 'toku', hiragana: 'とく', english: ' '},
        {key: '190', kanji: ' ', romaji: 'a', hiragana: 'あ', english: ' '},
        {key: '191', kanji: ' ', romaji: 'noku', hiragana: 'んおく', english: ' '},
        {key: '192', kanji: ' ', romaji: 'ta', hiragana: 'た', english: ' '},
        {key: '193', kanji: ' ', romaji: 'ra', hiragana: 'ら', english: ' '},
        {key: '194', kanji: ' ', romaji: 'sam', hiragana: 'さっ', english: ' '},
        {key: '195', kanji: ' ', romaji: 'myaku', hiragana: 'みゃく', english: ' '},
        {key: '196', kanji: ' ', romaji: 'sam', hiragana: 'さん', english: ' '},
        {key: '197', kanji: ' ', romaji: 'bo', hiragana: 'ぼ', english: ' '},
        {key: '198', kanji: ' ', romaji: 'dai', hiragana: 'だい', english: ' '},
        {key: '199', kanji: ' ', romaji: 'ko', hiragana: 'こ', english: ' '},
        {key: '200', kanji: ' ', romaji: 'chi', hiragana: 'ち', english: ' '},
        {key: '201', kanji: ' ', romaji: 'han', hiragana: 'はん', english: ' '},
        {key: '202', kanji: ' ', romaji: 'nya', hiragana: 'にゃ', english: ' '},
        {key: '203', kanji: ' ', romaji: 'ha', hiragana: 'は', english: ' '},
        {key: '204', kanji: ' ', romaji: 'ra', hiragana: 'ら', english: ' '},
        {key: '205', kanji: ' ', romaji: 'mi', hiragana: 'み', english: ' '},
        {key: '206', kanji: ' ', romaji: 'ta', hiragana: 'た', english: ' '},
        {key: '207', kanji: ' ', romaji: 'ze', hiragana: 'ぜ', english: ' '},
        {key: '218', kanji: ' ', romaji: 'dai', hiragana: 'だい', english: ' '},
        {key: '219', kanji: ' ', romaji: 'jin', hiragana: 'じん', english: ' '},
        {key: '210', kanji: ' ', romaji: 'shu', hiragana: 'す', english: ' '},
        {key: '211', kanji: ' ', romaji: 'ze', hiragana: 'ぜ', english: ' '},
        {key: '212', kanji: ' ', romaji: 'dai', hiragana: 'だい', english: ' '},
        {key: '213', kanji: ' ', romaji: 'myo', hiragana: 'みょ', english: ' '},
        {key: '214', kanji: ' ', romaji: 'shu', hiragana: 'す', english: ' '},
        {key: '215', kanji: ' ', romaji: 'ze', hiragana: 'ぜ', english: ' '},
        {key: '216', kanji: '無', romaji: 'mu', hiragana: 'む', english: 'No'},
        {key: '217', kanji: ' ', romaji: 'jo', hiragana: 'じょ', english: ' '},
        {key: '228', kanji: ' ', romaji: 'shu', hiragana: 'す', english: ' '},
        {key: '229', kanji: ' ', romaji: 'ze', hiragana: 'ぜ', english: ' '},
        {key: '220', kanji: '無', romaji: 'mu', hiragana: 'む', english: 'No'},
        {key: '221', kanji: ' ', romaji: 'to', hiragana: 'と', english: ' '},
        {key: '222', kanji: ' ', romaji: 'do', hiragana: 'ど', english: ' '},
        {key: '223', kanji: ' ', romaji: 'shu', hiragana: 'す', english: ' '},
        {key: '224', kanji: ' ', romaji: 'no', hiragana: 'の', english: ' '},
        {key: '225', kanji: ' ', romaji: 'jo', hiragana: 'じょ', english: ' '},
        {key: '226', kanji: ' ', romaji: 'is', hiragana: 'いっ', english: ' '},
        {key: '227', kanji: ' ', romaji: 'sai', hiragana: 'さい', english: ' '},
        {key: '238', kanji: ' ', romaji: 'ku', hiragana: 'く', english: ' '},
        {key: '239', kanji: '心', romaji: 'shin', hiragana: 'しん', english: 'heart'},
        {key: '230', kanji: ' ', romaji: 'jitsu', hiragana: 'じつ', english: ' '},
        {key: '231', kanji: ' ', romaji: 'fu', hiragana: 'ふ', english: ' '},
        {key: '232', kanji: ' ', romaji: 'ko', hiragana: 'こ', english: ' '},
        {key: '233', kanji: ' ', romaji: 'ko', hiragana: 'こ', english: ' '},
        {key: '234', kanji: ' ', romaji: 'setsu', hiragana: 'せつ', english: ' '},
        {key: '235', kanji: ' ', romaji: 'han', hiragana: 'はん', english: ' '},
        {key: '236', kanji: ' ', romaji: 'nya', hiragana: 'にゃ', english: ' '},
        {key: '237', kanji: ' ', romaji: 'ha', hiragana: 'は', english: ' '},
        {key: '248', kanji: ' ', romaji: 'ra', hiragana: 'ら', english: ' '},
        {key: '249', kanji: ' ', romaji: 'mit', hiragana: 'みっ', english: ' '},
        {key: '240', kanji: ' ', romaji: 'ta', hiragana: 'た', english: ' '},
        {key: '241', kanji: ' ', romaji: 'shu', hiragana: 'す', english: ' '},
        {key: '242', kanji: ' ', romaji: 'soku', hiragana: 'そく', english: ' '},
        {key: '243', kanji: ' ', romaji: 'setsu', hiragana: 'せつ', english: ' '},
        {key: '244', kanji: ' ', romaji: 'shu', hiragana: 'す', english: ' '},
        {key: '245', kanji: ' ', romaji: 'watsu', hiragana: 'わつ', english: ' '},
        {key: '246', kanji: ' ', romaji: 'gya', hiragana: 'ぎゃ', english: ' '},
        {key: '247', kanji: ' ', romaji: 'te', hiragana: 'て', english: ' '},
        {key: '258', kanji: ' ', romaji: 'gya', hiragana: 'ぎゃ', english: ' '},
        {key: '259', kanji: ' ', romaji: 'te', hiragana: 'て', english: ' '},
        {key: '250', kanji: ' ', romaji: 'ha', hiragana: 'は', english: ' '},
        {key: '251', kanji: ' ', romaji: 'ra', hiragana: 'ら', english: ' '},
        {key: '252', kanji: ' ', romaji: 'gya', hiragana: 'ぎゃ', english: ' '},
        {key: '253', kanji: ' ', romaji: 'te', hiragana: 'て', english: ' '},
        {key: '254', kanji: ' ', romaji: 'hara', hiragana: 'はら', english: ' '},
        {key: '255', kanji: ' ', romaji: 'so', hiragana: 'そ', english: ' '},
        {key: '256', kanji: ' ', romaji: 'gya', hiragana: 'ぎゃ', english: ' '},
        {key: '257', kanji: ' ', romaji: 'te', hiragana: 'て', english: ' '},
        {key: '268', kanji: ' ', romaji: 'bo', hiragana: 'ぼ', english: ' '},
        {key: '269', kanji: ' ', romaji: 'ji', hiragana: 'じ', english: ' '},
        {key: '260', kanji: ' ', romaji: 'sowa', hiragana: 'そわ', english: ' '},
        {key: '261', kanji: ' ', romaji: 'ka', hiragana: 'か', english: ' '},
        {key: '262', kanji: ' ', romaji: 'han', hiragana: 'はん', english: ' '},
        {key: '263', kanji: ' ', romaji: 'nya', hiragana: 'にゃ', english: ' '},
        {key: '264', kanji: '心', romaji: 'shin', hiragana: 'しん', english: 'heart'},
        {key: '265', kanji: '經', romaji: 'gyo', hiragana: 'ぎょ', english: ' '}
    ],
    title: [
        {key: '001', kanji: '摩訶', romaji: 'Maka', hiragana: 'まか', english: 'Great'},
        {key: '002', kanji: '般若', romaji: 'Hannya', hiragana: 'はんにゃ', english: 'Wisdom'},
        {key: '003', kanji: '波羅蜜多', romaji: 'Haramitta', hiragana: 'はらみった', english: 'Perfect'},
        {key: '004', kanji: '心', romaji: 'Shin', hiragana: 'しん', english: 'Heart'},
        {key: '005', kanji: '經', romaji: 'Gyo', hiragana: 'ぎょ', english: 'Sutra'}
    ]
};

module.exports = heartsutra;